[workspace]
members = [
    "asset-system",
    "let-engine-core",
    "let-engine-audio",
    "let-engine-widgets",
    "let-engine",
]
resolver = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"

[workspace.dependencies]
parking_lot = "0.12"
ahash = "0.8"
anyhow = "1.0"
thiserror = "1.0"
bincode = "1.3"
once_cell = "1.19"
derive_builder = "0.20"
crossbeam = "0.8"

  [workspace.dependencies.glam]
  version = "0.28"

  [workspace.dependencies.nalgebra]
  version = "0.33"
  
  [workspace.dependencies.vulkano]
  version = "0.34"
  git = "https://github.com/vulkano-rs/vulkano.git"

  [workspace.dependencies.egui_winit_vulkano]
  version = "0.27"
  git = "https://github.com/Letronix624/egui_winit_vulkano.git"

  [workspace.dependencies.winit]
  version = "0.29"

  [workspace.dependencies.rapier2d]
  version = "0.21"

  [workspace.dependencies.image]
  version = "0.25"

  [workspace.dependencies.serde]
  version = "1.0"

  [workspace.dependencies.flate2]
  version = "1.0"

  [workspace.dependencies.bzip2]
  version = "0.4"

  [workspace.dependencies.zstd]
  version = "0.13"

  [workspace.dependencies.xz2]
  version = "0.1"

  [workspace.dependencies.lz4]
  version = "1.24"

