[package]
name = "let-engine"
version = "0.2.0"
authors = ["Let"]
edition = "2021"
description = "A game engine to learn vulkan made by Let. Not done yet."
readme = "README.md"
repository = "https://github.com/Letronix624/Let-Engine"
keywords = [
    "gamedev",
    "graphics",
    "engine"
]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.32.3"
vulkano-win = "0.32.0"
vulkano-shaders = "0.31.1"
bytemuck = "1.8.0"
winit = "0.27.5"
image = "0.24.4"
rodio = "0.16.0"
png = "0.17.7"
discord-presence = "0.5.14"
rusttype = { version = "0.9.3", features = ["gpu_cache"]}
error-stack = "0.3.0"
hashbrown = "0.13.2"
tokio = "1.26.0"

[profile.release]
strip = "symbols"
opt-level = 3
lto = "fat"
codegen-units = 1
