[package]
name = "let-engine"
version = "0.4.2"
authors = ["Let"]
edition = "2021"
description = "A game engine to learn vulkan made by Let. Not done yet."
readme = "README.md"
repository = "https://github.com/Letronix624/Let-Engine"
keywords = [
    "gamedev",
    "graphics",
    "engine"
]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.33.0"
vulkano-win = "0.33.0"
vulkano-shaders = "0.33.0"
winit = "0.28.5"
image = "0.24.6"
rodio = "0.16.0"
error-stack = "0.3.1"
hashbrown = "0.13.2"
parking_lot = "0.12.1"
anyhow = "1.0.70"
thiserror = "1.0.40"
derive_builder = "0.12.0"
indexmap = "1.9.3"
atomic_float = "0.1.0"
glam = "0.24.0"
crossbeam = "0.8.2"
syn = "2.0.16"
quote = "1.0.27"
rusttype = { version = "0.9.3", features = [ "gpu_cache" ] }
egui_winit_vulkano = { version = "0.24.0", optional = true }
rapier2d = { version = "0.17.2", features = [ "simd-stable" ], optional = true}

[features]
egui = ["dep:egui_winit_vulkano"]
physics = ["dep:rapier2d"]

[profile.release]
strip = "symbols"
opt-level = 3
lto = "fat"
codegen-units = 1
