[package]
name = "let-engine"
version = "0.7.1"
authors = ["Let"]
edition = "2021"
description = "A simple 2d game engine."
readme = "../README.md"
repository = "https://github.com/Letronix624/Let-Engine"
documentation = "https://let-server.net/docs/let_engine"
keywords = [
    "gamedev",
    "graphics",
    "engine"
]
license = "Apache-2.0"

[dependencies]
vulkano = "0.34"
winit = "0.28"
image = "0.24"

#rodio = "0.17.1"
#error-stack = "0.3.1"

anyhow = "1.0"
thiserror = "1.0"

hashbrown = "0.14"
parking_lot = "0.12"
derive_builder = "0.12"
indexmap = "2.0"
atomic_float = "0.1"
crossbeam = "0.8"
once_cell = "1.18"

glam = { version = "0.24.2", features = [ "bytemuck" ] }
nalgebra = { version = "0.32.3", features = [ "convert-glam024" ] }

rusttype = { version = "0.9.3", features = [ "gpu_cache" ] }
egui_winit_vulkano = { git = "https://github.com/Letronix624/egui_winit_vulkano.git", optional = true }
rapier2d = { version = "0.17.2", features = [ "simd-stable" ]}
paste = "1.0.14"

[features]
default = []
egui = ["dep:egui_winit_vulkano"]
vulkan_debug_utils = []

[package.metadata.docs.rs]

features = ["egui"]

default-target = "x86_64-unknown-linux-gnu"