[package]
name = "let-engine"
version = "0.1.0-alpha"
authors = ["Let"]
edition = "2021"
description = "A game engine to learn vulkan made by Let. Not done yet."
readme = "../README.md"
repository = "https://github.com/Letronix624/Let-Engine"
documentation = "https://let-server.net/docs/let_engine"
keywords = [
    "gamedev",
    "graphics",
    "engine"
]
license = "Apache-2.0"

[dependencies]
vulkano = "0.33.0"
vulkano-win = "0.33.0"
vulkano-shaders = "0.33.0"
winit = "0.28.6"
image = "0.24.7"
color-art = "0.3.7"

#rodio = "0.17.1"
#error-stack = "0.3.1"

anyhow = "1.0.75"
thiserror = "1.0.48"

hashbrown = "0.14.0"
parking_lot = "0.12.1"
derive_builder = "0.12.0"
indexmap = "2.0.0"
atomic_float = "0.1.0"
crossbeam = "0.8.2"
once_cell = "1.18"

glam = { version = "0.24.2", features = [ "bytemuck" ] }
nalgebra = { version = "0.32.3", features = [ "convert-glam024" ] }

engine-macros = { path = "../engine-macros", version = "0.3.*" }

rusttype = { version = "0.9.3", features = [ "gpu_cache" ] }
egui_winit_vulkano = { version = "0.25.0", optional = true }
rapier2d = { version = "0.17.2", features = [ "simd-stable" ]}
paste = "1.0.14"

[features]
default = []
egui = ["dep:egui_winit_vulkano"]
