[package]
name = "let-engine"
version = "0.5.0"
authors = ["Let"]
edition = "2021"
description = "A game engine to learn vulkan made by Let. Not done yet."
readme = "../README.md"
repository = "https://github.com/Letronix624/Let-Engine"
keywords = [
    "gamedev",
    "graphics",
    "engine"
]
license = "Apache-2.0"

[dependencies]
vulkano = "0.33.0"
vulkano-win = "0.33.0"
vulkano-shaders = "0.33.0"
winit = "0.28.6"
image = "0.24.6"

#rodio = "0.17.1"

#error-stack = "0.3.1"
anyhow = "1.0.71"
thiserror = "1.0.40"

hashbrown = "0.13.2"
parking_lot = "0.12.1"
derive_builder = "0.12.0"
indexmap = "1.9.3"
atomic_float = "0.1.0"
crossbeam = "0.8.2"
glam = { version = "0.23.0", features = [ "bytemuck" ] }
nalgebra = { version = "0.32.2", features = [ "convert-glam023" ] }

engine-macros = { path = "../engine-macros", version = "0.1.0" }

rusttype = { version = "0.9.3", features = [ "gpu_cache" ] }
egui_winit_vulkano = { version = "0.24.0", optional = true }
rapier2d = { version = "0.17.2", features = [ "simd-stable" ]}

[features]
egui = ["dep:egui_winit_vulkano"]

