[package]
name = "let-engine"
version = "0.11.0"
authors = [ "let" ]
edition = "2021"
description = "game engine"
readme = "../README.md"
repository = "https://github.com/Letronix624/let-engine"
keywords = [ "gamedev", "graphics", "engine" ]
license = "Apache-2.0"

[package.metadata.docs.rs]
features = [ "egui" ]
default-target = "x86_64-unknown-linux-gnu"

[dependencies]
parking_lot = { workspace = true }
ahash = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
derive_builder = { workspace = true }
crossbeam = { workspace = true }
atomic_float = "0.1"
spin_sleep = "1.2"
once_cell = { workspace = true }

  [dependencies.vulkano]
  workspace = true
  optional = true

  [dependencies.winit]
  workspace = true
  optional = true

  [dependencies.image]
  workspace = true
  optional = true

  [dependencies.egui_winit_vulkano]
  workspace = true
  optional = true

  [dependencies.kira]
  version = "0.8"
  optional = true

  [dependencies.glam]
  workspace = true
  features = [ "bytemuck", "mint" ]

  [dependencies.nalgebra]
  version = "0.32.4"
  features = [ "convert-glam025" ]

  [dependencies.rapier2d]
  workspace = true
  features = [ "simd-stable" ]
  optional = true

  [dependencies.asset-system]
  version = "0.1"
  path = "../asset-system"
  optional = true

  [dependencies.let-engine-core]
  version = "0.11"
  path = "../let-engine-core"

[dev-dependencies]
egui_demo_lib = "0.27"

[features]
default = [ "client", "labels", "physics", "audio" ]
egui = [ "let-engine-core/egui", "dep:egui_winit_vulkano", "client" ]
vulkan_debug_utils = [ "let-engine-core/vulkan_debug_utils" ]
client = [ "dep:vulkano", "dep:winit", "dep:image", "let-engine-core/client" ]
labels = [ "client", "let-engine-core/labels" ]
audio = [ "dep:kira", "client" ]
physics = [ "dep:rapier2d" ]
asset_system = [ "dep:asset-system" ]
serde = [ "glam/serde", "let-engine-core/serde" ]

rand = [ "glam/rand", "let-engine-core/rand" ]
fast-math = [ "glam/fast-math", "let-engine-core/fast-math" ]

# asset system compression algorithms
deflate = [ "asset-system/deflate" ]
bzip2 = [ "asset-system/bzip2" ]
zstd = [ "asset-system/zstd" ]
lzma = [ "asset-system/lzma" ]
lz4 = [ "asset-system/lz4" ]

