[package]
name = "let-engine"
version = "0.10.0"
authors = [ "let" ]
edition = "2021"
description = "game engine"
readme = "../README.md"
repository = "https://github.com/Letronix624/let-engine"
keywords = [ "gamedev", "graphics", "engine" ]
license = "Apache-2.0"

[package.metadata.docs.rs]
features = [ "egui" ]
default-target = "x86_64-unknown-linux-gnu"

[dependencies]
parking_lot = { workspace = true }
ahash = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
derive_builder = "0.20"
indexmap = "2.2"
atomic_float = "0.1"
crossbeam = "0.8"
paste = "1.0.14"
spin_sleep = "1.2"
once_cell = { workspace = true }

  [dependencies.vulkano]
  version = "0.34"
  git = "https://github.com/vulkano-rs/vulkano.git"
  optional = true

  [dependencies.winit]
  version = "0.29"
  optional = true

  [dependencies.image]
  version = "0.25"
  optional = true

  [dependencies.glyph_brush]
  version = "0.7.8"
  optional = true

  [dependencies.egui_winit_vulkano]
  version = "0.27"
  git = "https://github.com/Letronix624/egui_winit_vulkano.git"
  optional = true

  [dependencies.kira]
  version = "0.8"
  optional = true

  [dependencies.glam]
  version = "0.25"
  features = [ "bytemuck", "mint" ]

  [dependencies.nalgebra]
  version = "0.32.4"
  features = [ "convert-glam025" ]

  [dependencies.rapier2d]
  version = "0.18"
  features = [ "simd-stable" ]
  optional = true

  [dependencies.asset-system]
  version = "0.1"
  path = "../asset-system"
  optional = true

[dev-dependencies]
egui_demo_lib = "0.26"

[features]
default = [ "client", "labels", "physics", "audio" ]
egui = [ "dep:egui_winit_vulkano", "client" ]
vulkan_debug_utils = [ ]
client = [ "dep:vulkano", "dep:winit", "dep:image" ]
labels = [ "dep:glyph_brush", "client" ]
audio = [ "dep:kira", "client" ]
physics = [ "dep:rapier2d" ]
asset_system = [ "dep:asset-system" ]
serde = [ "glam/serde" ]

rand = [ "glam/rand" ]
fast-math = [ "glam/fast-math" ]

# asset system compression algorithms
deflate = [ "asset-system/deflate" ]
bzip2 = [ "asset-system/bzip2" ]
zstd = [ "asset-system/zstd" ]
lzma = [ "asset-system/lzma" ]
lz4 = [ "asset-system/lz4" ]

