name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev build-essential cmake libvulkan-dev libasound2-dev libfontconfig1-dev
      - uses: actions/checkout@v3
      - name: Rust Linux Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-rust-linux"
      - name: Build
        run: cargo build --all-features --verbose
      - name: Examples
        run: cargo build --examples --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --verbose

  windows:
    runs-on: windows-latest
    steps:
      - name: Ninja Install
        run: pip install ninja
      - uses: actions/checkout@v3
      - name: Rust Windows Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-rust-windows"
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --verbose
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Macos Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-rust-macos"
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --verbose
